name: Build and Push Docker Image

on:
  workflow_dispatch:
  schedule:
    # 每天9点半执行
    - cron:  '0 0 * * 2,5'
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: airpods/pikpak_auto_invite:1
        platforms: linux/amd64,linux/arm64

